- id: doi:10.1007/s10936-024-10086-5
  title: "It costs to exist: Acceptability judgments of the temporal concord of the auxiliary verbs you and hui in Taiwan Mandarin"
- id: doi:10.5070/G60111432
- id: doi:10.1017/langcog.2023.49
  date: 2024-09-01
- id: doi:10.1075/consl.21046.col
  title: "Expressing the existence of an event with ‘<i>you</i> (to have) + VP’ in Taiwan Mandarin"
- id: doi:10.1075/intp.00069.fan
  title: "When two languages are competing: An ERP study of sentence processing in expert and novice interpreters"
- id: doi:10.1016/j.jneuroling.2021.100998
- id: doi:10.1163/2772_5766_hflo_com_202230
  title: "Experimental linguistics embracing linguistic diversity: On the contributions of Formosan languages to models of sentence processing"
  authors: Aymeric Collart
  date: 2024-01-02
  publisher: "Handbook of Formosan languages: The indigenous languages of Taiwan"
# ...more sources